apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ingress-nginx
  namespace: monitoring
spec:
  namespaceSelector: { matchNames: ["ingress-nginx"] }
  selector:
    matchLabels:
      app.kubernetes.io/name: ingress-nginx
      app.kubernetes.io/component: controller
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 15s
