apiVersion: kiali.io/v1alpha1
kind: Kiali
metadata:
  name: kiali
  namespace: istio-system
spec:
  auth:
    strategy: anonymous
  external_services:
    prometheus:
      url: http://monitoring-kube-prometheus-prometheus.monitoring.svc:9090
