apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: istio-proxies
  namespace: istio-system
  labels:
    release: kube-prometheus-stack   # <- change if your Helm release name differs
spec:
  namespaceSelector:
    any: true
  selector:
    matchExpressions:
      - key: istio.io/rev
        operator: Exists
  podMetricsEndpoints:
    - path: /stats/prometheus
      interval: 15s
      relabelings:
        - action: keep
          sourceLabels: [__meta_kubernetes_pod_container_name]
          regex: istio-proxy
        - action: replace
          targetLabel: __address__
          sourceLabels: [__meta_kubernetes_pod_ip]
          replacement: $1:15090

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istiod
  namespace: istio-system
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames: ["istio-system"]
  selector:
    matchLabels:
      app: istiod
  endpoints:
    - port: http-monitoring
      interval: 15s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-ingressgateway
  namespace: istio-system
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames: ["istio-system"]
  selector:
    matchLabels:
      istio: ingressgateway
  endpoints:
    - port: http-envoy-prom
      interval: 15s

---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-egressgateway
  namespace: istio-system
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames: ["istio-system"]
  selector:
    matchLabels:
      istio: egressgateway
  endpoints:
    - port: http-envoy-prom
      interval: 15s
